# Generated by Django 4.2.7 on 2023-11-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назавание')),
                ('tasks', models.TextField(verbose_name='Задача')),
            ],
        ),
        migrations.CreateModel(
            name='Task_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_add', models.CharField(max_length=50, verbose_name='Назавание')),
                ('tasks_add', models.TextField(verbose_name='Задача')),
            ],
        ),
    ]
